name: Output info
on:
  push:
  release:
    types: [published]
jobs:
  info:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"
      - name: Output release tag
        run: echo "${{ steps.get_tag_name.outputs.tag_name }}"
