name: Output info
on:
  push:
  release:
    types: [published]
jobs:
  info:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Output release tag
        run: echo  "$TAG_NAME"
