name: Output info
on:
  push:
  release:
    types: [published]
jobs:
  info:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ github.ref }}"
